### ISSUE TITLE
Metadata's `files` key missing version

### ISSUE THREAD

**Issue by sghill** [jjohannes/gradle-module-metadata-maven-plugin#10]
Hi,

Is there a way to modify files before they are uploaded? Or ensure that the deployment path to a file is used in the metadata?

I recently added this to the Jenkins okhttp-api plugin in order to publish the okhttp-bom platform. Consuming the next release unfortunately fails with:

```
> Could not find okhttp-api.hpi (io.jenkins.plugins:okhttp-api:4.9.3-105.vb96869f8ac3a).
```

Looking at the [published artifacts for okhttp-api:4.9.3-105.vb96869f8ac3a](https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugins/okhttp-api/4.9.3-105.vb96869f8ac3a/), both variants' files are missing the version:
```json
      "files": [
        {
          "name": "okhttp-api.hpi",
          "url": "okhttp-api.hpi",
          "size": 2593838,
          "sha512": "f9532abaa11e7a0afd0222dc6b32ec2df3a2940cd847caef23ae12841974407a1807f7e163de01d553bbcf3418a7a79b1264f970ba9baf29fb86b64da27d044e",
          "sha256": "6b5cf02b0faa6df2f9615bd249f472283326886d3cbe824f11933d17eb5e1809",
          "sha1": "5ce092c3f21b67a6aa0cd413933243d32d3b80fe",
          "md5": "887998f3e92fab5f6856495c554d59e1"
        }
      ]
```

The release happened [on GitHub Actions](https://github.com/jenkinsci/okhttp-api-plugin/runs/4371171706?check_suite_focus=true) by running:
```
mvn -B -V -s /home/runner/work/_actions/jenkins-infra/jenkins-maven-cd-action/v1.2.0/settings.xml -ntp -Dstyle.color=always -Dset.changelist -DaltDeploymentRepository=maven.jenkins-ci.org::default::https://repo.jenkins-ci.org/releases/ -Pquick-build '-P!consume-incrementals' clean deploy
```

The `hpi` goal does actually produce a file without a version:
```
[INFO] --- maven-hpi-plugin:3.20:hpi (default-hpi) @ okhttp-api ---
... [omitted for brevity] ...
[INFO] Generating hpi /home/runner/work/okhttp-api-plugin/okhttp-api-plugin/target/okhttp-api.hpi
```
But it is ultimately installed and deployed with a version:
```
[INFO] --- maven-install-plugin:3.0.0-M1:install (default-install) @ okhttp-api ---
[INFO] Installing /home/runner/work/okhttp-api-plugin/okhttp-api-plugin/target/okhttp-api.hpi to /home/runner/.m2/repository/io/jenkins/plugins/okhttp-api/4.9.3-105.vb96869f8ac3a/okhttp-api-4.9.3-105.vb96869f8ac3a.hpi
```

**Comment by jjohannes** [comment]
Thanks for reporting @sghill. There are similar issues in Gradle, when the publishing changes the file name "last minute" to conform to Maven standards. Looks like the same is going on here.

I did some research and if I understand correctly, the name is changed late in aether - SimpleLocalRepositoryManager.getPathForArtifact() - right before the file is uploader. That's similar to how it works in Gradle.

That's too late to get that name, because the metadata File already needs to exist at that point.

So what I did instead is calculating the name the file _will have_ in the Metadata Writer (c8f8b08eaca6a8466c9ee8bdfc9dd1c53aaecd53). Hope this is the right fix.

I'll see that I get out a new release of the plugin soon. Maybe you can verify if things work for you now, by locally installing this plugin (`main` is now `0.3.0`).

**Comment by sghill** [comment]
Hi @jjohannes, thanks for the fix here!

I was able to publish this plugin locally and use it in okhttp-api for a local publish. Verified it produced the `files` key correctly and that it was resolvable when consuming with Gradle Module Metadata.

**Comment by jjohannes** [comment]
Thanks @sghill. `0.3.0` has been released.
